### ISSUE TITLE
plugin folder must be named wpdb_import

### ISSUE THREAD

**Issue by tvon** [jbleuzen/Wolf_WPDB_Import#1]
I don't think this is mentioned anywhere, but if you do a git clone directly to your plugins folder (named Wolf_WPDB_Import) you'll end up with a plugin that shows up but doesn't work when activated.  It needs to be named 'wpdb_import' to work as it is referenced as such in the code.

**Comment by dajare** [comment]
More a Github "issue" than one for the plugin, but yes -- this is worth telling users!

You can see it's the [first instruction in the CKEditor "readme"](https://github.com/dajare/wolf_ckeditor#readme). Maybe worth including for this excellent plugin, too?

**Comment by jbleuzen** [comment]
Yeah sorry about that. I've added extra instructions in the readme as David suggest.

Closing the issue :)

Thanks for your report tvon !
